### ISSUE TITLE
Add sensible defaults

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205#13]
We need to add some sensible defaults for the filters. Here's are the proposed defaults:

- Genres
  - Action
  - Adventure
  - Comedy
  - Drama
  - Horror
  - Romantic Comedy
  - Thriller/Suspense

- MPAA Ratings
  - PG
  - PG-13
  - R

- Years
  - 2000 to 2011

**Comment by sreejithmunthikodu** [comment]
Sounds good. For years, I would prefer adding the full range as the default.

**Comment by sreejithmunthikodu** [comment]
Defaults working well
