### ISSUE TITLE
Should we scrap the interactivity between the top and bottom charts?

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/DSCI_532_group_205#14]
It looks like the top-bottom chart interactivity is not adding any value to the app. When clicked on a bar, the interactivity is supposed to highlight the respective scatter in the scatterplot. But by default, we are highlighting all the top 10 movies. So I feel the extra interactivity would make the coding a bit complex without much value addition.

**Comment by techrah** [comment]
The initial idea was that when one movie was selected, everything else would fade into the background. I have been working on this and I have the selector working in the bar chart but I've not yet been able to get the scatter plot chart to react to the changes. I'll try a bit more tomorrow to see how far I can get but you are right in that it no longer seems to provide as much value as we initially thought.
