### ISSUE TITLE
Reflections

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205#19]
@sreejithmunthikodu @fkhan72 

Let's add ideas here for our REFLECTIONS document

**Comment by sreejithmunthikodu** [comment]
TA Comments
1. Work was equally distributed among all the team members. All got the chance to make pull requests with their part of the work. Also, team members were free to make changes to tasks assigned to other members also. It was a good teamwork. All members first focused on their assigned tasks and later contributed to other's work as well. So there are sufficient pull requests from all team members.

2. All team members tried to make all commit messages meaningful by reflecting the changes in that particular commit.

3. We primarily used Github issues as the mode of communication. Issues were created where feedbacks or suggestions were required from each team member.

**Comment by sreejithmunthikodu** [comment]
Strengths of our app
1. The final app version met all the requirements listed in the project proposal. The app matched the sketch included in the proposal. 
2. The app is successfully deployed on Heroku. It can now be used as an effective tool to select what movies to watch.

Limitations
1. The styling of the app can be improved. However, with the limited time, we have managed to come up with styling and layout that are simple and elegant. Our major focus in this project was to add all the functionalities listed in the project proposal.

**Comment by techrah** [comment]
Issues that may not be resolved for this release:

- When selecting a movie that has a greyish or pale colour, it's hard to see that it has been selected. I tried, but was not able to figure out how to reduce the opacity of the colour of the unselected movies.
- The layout had to be made large enough to properly accommodate the charts. Depending on the user's screen size, some scrolling may be necessary in the vertical and/or horizontal directions.
- The lower chart has a lot of whitespace on its left side. This is because Altair is lining up the charts vertically based on the y-axis. I was not able to override this.

**Comment by sreejithmunthikodu** [comment]
Future Improvements
1. We should add more styling and improve the layout of the app.
