### ISSUE TITLE
Remove legend all-together

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205#20]
I've gotten the interaction to work between the two charts. However, the top chart is heavy with text on both sides. I wish I could move the legend to the lower chart but I'm not sure that's possible.

The chart looks like this when a single movie is selected.

![image](https://user-images.githubusercontent.com/600471/69903711-0d52d600-1352-11ea-8a6d-66b98e55d2f6.png)

I'm thinking of just removing the legend all-together because the information is already on the left side of the upper chart with all the same colour encodings. Do you agree that we can remove it without affecting the information available?

**Comment by sreejithmunthikodu** [comment]
Great work Ryan. 
I totally agree we should remove legend from both the plots. It is redundant.

**Comment by sreejithmunthikodu** [comment]
For handling `NaN` in the ratings, we have two other options compared to the current version.
1. drop nas from top chart as well for non-rated movies
2. fill na in the rating with the mean across all movies

what is more appropriate?

**Comment by techrah** [comment]
Ok, I'll work on removing the legends and adjusting the UI.

**Comment by sreejithmunthikodu** [comment]
legends removed, nans dropped
