### ISSUE TITLE
How to handle Nans?

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/DSCI_532_group_205#21]
For handling NaN in the ratings, we have two other options compared to the current version.

1. drop nas from top chart as well for non-rated movies
2. fill na in the rating with the mean across all movies
3. what is more appropriate?

**Comment by techrah** [comment]
Not sure how 2 would work. I say we just go with 1 for now.

**Comment by sreejithmunthikodu** [comment]
sounds good.

**Comment by sreejithmunthikodu** [comment]
Nans removed from both plots. Colors now match in both the plots.
