### ISSUE TITLE
Can we change silver colour for movie colours?

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205#23]
![image](https://user-images.githubusercontent.com/600471/69904418-04b2cd80-135b-11ea-9741-2e5ebffae4a2.png)

Notice the silver/grey colour? When this move is selected, it's hard to see that it is selected because I make all other colour go grey.

![image](https://user-images.githubusercontent.com/600471/69904443-388df300-135b-11ea-9a7f-ba440286cc55.png)

Can we change the colour palette to not use that colour?

**Comment by sreejithmunthikodu** [comment]
How about scheme="tableau10"?

**Comment by techrah** [comment]
This scheme still has a very pale value :(

**Comment by sreejithmunthikodu** [comment]
I think we are out of options here....
https://vega.github.io/vega/docs/schemes/
Can you try chaning the opacity to a very low value?

**Comment by techrah** [comment]
My previous attempts to set an alpha value failed. I'll try a bit long and if I can't fix it, we'll just document that in our reflections.

**Comment by sreejithmunthikodu** [comment]
Sure. I suggest we stop here and deploy.

**Comment by techrah** [comment]
Yes, I will check in what I have before working on this issue.

**Comment by techrah** [comment]
Due to lack of time, I will add this issue in reflections
