### ISSUE TITLE
Upper Chart Interactivity Fixes

### ISSUE THREAD

**Issue by techrah** [UBC-MDS/DSCI_532_group_205#34]
- Can we use a single colour for upper chart?
- Can we start off with no movies selected (all grey)?
- Add instructions so user knows to select a movie.
- Remove interactivity from both charts
- Perhaps only show one single large dot for movie selected since we only have one colour now and it'll be hard to match movies with dots.

**Comment by sreejithmunthikodu** [comment]
closing the issue as original version is better. Closed PR #39
