### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/DSCI_532_group_205#9]
Here are some comments you could include in order to not loose marks:
* Ensure everyone is getting a chance to code and submit pull requests, and that work is being distributed equally.
* Some commit messages are not informative enough, for example “updates”.
* Moving forward, remember to communicate with your team by creating new Issues or using Github projects functionality.

**Comment by techrah** [comment]
These issues have been addressed as noted in #19 and in the `reflections.md` document.
